# Alertmanager Configuration for Reddit Sentiment Pipeline
# Production alerting configuration with GitHub integration

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@cicd-project.local'
  github_api_url: 'https://api.github.com/'

# Routing configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-receiver'
  routes:
    # Critical alerts go to GitHub issues immediately
    - match:
        severity: critical
      receiver: 'github-critical'
      group_wait: 30s
      repeat_interval: 30m
    
    # Warning alerts get grouped and sent to GitHub
    - match:
        severity: warning
      receiver: 'github-warning'
      group_wait: 2m
      repeat_interval: 2h
    
    # Service-specific routing
    - match:
        service: reddit-sentiment-pipeline
      receiver: 'github-pipeline'
      continue: true

# Alert inhibition rules
inhibit_rules:
  # Inhibit warning alerts when critical alert is firing for same service
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance']

# Receiver configurations
receivers:
  # Default receiver
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://localhost:9093/webhook/default'
        send_resolved: true
        title: 'Reddit Sentiment Pipeline Alert'
        text: 'Alert: {{ .GroupLabels.alertname }}'

  # GitHub critical alerts
  - name: 'github-critical'
    webhook_configs:
      - url: 'http://localhost:8080/webhook/github'
        send_resolved: true
        http_config:
          bearer_token: '${GITHUB_TOKEN_PAT}'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          **CRITICAL ALERT**
          
          **Service:** {{ .GroupLabels.service }}
          **Alert:** {{ .GroupLabels.alertname }}
          **Status:** {{ .Status }}
          **Severity:** {{ .CommonLabels.severity }}
          
          **Details:**
          {{ range .Alerts }}
          - **Instance:** {{ .Labels.instance }}
          - **Description:** {{ .Annotations.description }}
          - **Started:** {{ .StartsAt }}
          {{ end }}
          
          **Runbook:** {{ .CommonAnnotations.runbook_url }}
          
          Please investigate immediately!

  # GitHub warning alerts
  - name: 'github-warning'
    webhook_configs:
      - url: 'http://localhost:8080/webhook/github'
        send_resolved: true
        http_config:
          bearer_token: '${GITHUB_TOKEN_PAT}'
        title: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        text: |
          **WARNING ALERT**
          
          **Service:** {{ .GroupLabels.service }}
          **Alert:** {{ .GroupLabels.alertname }}
          **Status:** {{ .Status }}
          **Severity:** {{ .CommonLabels.severity }}
          
          **Details:**
          {{ range .Alerts }}
          - **Instance:** {{ .Labels.instance }}
          - **Description:** {{ .Annotations.description }}
          - **Started:** {{ .StartsAt }}
          {{ end }}
          
          **Runbook:** {{ .CommonAnnotations.runbook_url }}

  # Pipeline-specific alerts
  - name: 'github-pipeline'
    webhook_configs:
      - url: 'http://localhost:8080/webhook/github'
        send_resolved: true
        http_config:
          bearer_token: '${GITHUB_TOKEN_PAT}'
        title: '📊 Pipeline Alert: {{ .GroupLabels.alertname }}'
        text: |
          **PIPELINE ALERT**
          
          **Service:** Reddit Sentiment Pipeline
          **Alert:** {{ .GroupLabels.alertname }}
          **Status:** {{ .Status }}
          
          **Metrics:**
          {{ range .Alerts }}
          - **Value:** {{ .Annotations.value }}
          - **Threshold:** {{ .Annotations.threshold }}
          - **Instance:** {{ .Labels.instance }}
          {{ end }}
          
          **Resolution Steps:**
          1. Check service status: `systemctl status reddit-sentiment-pipeline`
          2. Review logs: `journalctl -u reddit-sentiment-pipeline -f`
          3. Monitor metrics: Check Grafana dashboard
          4. Follow runbook: {{ .CommonAnnotations.runbook_url }}

# Templates for alert formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Webhook configuration for GitHub integration
webhook_config:
  github:
    api_url: 'https://api.github.com'
    repository: 'YasCay/cicd_project'
    token: '${GITHUB_TOKEN_PAT}'
    issue_labels: ['alert', 'monitoring', 'automated']
    assignees: ['YasCay']
