---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: reddit-sentiment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Reddit Sentiment Analysis Pipeline Project
  
  sourceRepos:
    - https://github.com/your-org/reddit-sentiment-pipeline
    - https://charts.bitnami.com/bitnami  # For dependencies
  
  destinations:
    - namespace: reddit-sentiment
      server: https://kubernetes.default.svc
    - namespace: reddit-sentiment-*
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: PersistentVolume
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: monitoring.coreos.com
      kind: ServiceMonitor
    - group: monitoring.coreos.com
      kind: PrometheusRule
  
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: batch
      kind: CronJob
    - group: policy
      kind: PodDisruptionBudget
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
  
  roles:
    - name: admin
      description: Admin access to reddit-sentiment project
      policies:
        - p, proj:reddit-sentiment:admin, applications, *, reddit-sentiment/*, allow
        - p, proj:reddit-sentiment:admin, repositories, *, *, allow
      groups:
        - reddit-sentiment-admins
    
    - name: developer
      description: Developer access to reddit-sentiment project
      policies:
        - p, proj:reddit-sentiment:developer, applications, get, reddit-sentiment/*, allow
        - p, proj:reddit-sentiment:developer, applications, sync, reddit-sentiment/*, allow
      groups:
        - reddit-sentiment-developers
  
  syncWindows:
    - kind: allow
      schedule: '0 9-17 * * 1-5'  # Business hours Mon-Fri
      duration: 8h
      applications:
        - reddit-sentiment-pipeline
      manualSync: true
    
    - kind: deny
      schedule: '0 0-8,18-23 * * *'  # Outside business hours
      duration: 10h
      applications:
        - reddit-sentiment-pipeline
      manualSync: false
