apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reddit-sentiment-pipeline.configMapName" . }}
  labels:
    {{- include "reddit-sentiment-pipeline.labels" . | nindent 4 }}
data:
  reddit-user-agent: {{ .Values.reddit.userAgent | quote }}
  reddit-subreddits: {{ .Values.reddit.subreddits | quote }}
  log-level: {{ .Values.logging.level | quote }}
  log-format: {{ .Values.logging.format | quote }}
  enable-metrics: {{ .Values.metrics.enabled | quote }}
  metrics-port: {{ .Values.metrics.port | quote }}
