{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "reddit-sentiment-pipeline.fullname" . }}
  labels:
    {{- include "reddit-sentiment-pipeline.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "reddit-sentiment-pipeline.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    path: /metrics
{{- end }}
